[package]
name = "doogie"
version = "1.0.0"
authors = ["Devin Smith <dsmith@polysync.io>"]
build = "build.rs"

[dependencies]
libc = "0.2.0"
try_from = "0.2.2"
env_logger = "0.5.10"
log = "0.4.2"
lazy_static = "1.0.1"

[dev-dependencies]
proptest = "0.3.3"

[build-dependencies]
cmake = "0.1"
